apiVersion: mesh.oauthd.com/v1
kind: Service
metadata:
  name: xxxxxx
  namespace: default
spec:
  version: v3
  image: nginx:alpine
  imagePullPolicy: IfNotPresent
  ports:
    - port: 80
      protocol: HTTP
      targetPort: 80
  weight: 30
