apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    objectset.rio.cattle.io/applied: '{"kind":"VirtualService","apiVersion":"networking.istio.io/v1alpha3","metadata":{"name":"xxxxxx-v3","namespace":"default","creationTimestamp":null,"labels":{"objectset.rio.cattle.io/hash":"6eddc47a0f5e8e59d253ec6022892f0331fffc0f"},"annotations":{"objectset.rio.cattle.io/id":"routing-service","objectset.rio.cattle.io/owner-gvk":"/,
      Kind=","objectset.rio.cattle.io/owner-name":"xxxxxx","objectset.rio.cattle.io/owner-namespace":"default"}},"spec":{"hosts":["xxxxxx-v3-default."],"gateways":["mesh","mesh-gateway.mesh-system.svc.cluster.local"],"http":[{"match":[{"port":9080,"gateways":["mesh","mesh-gateway.mesh-system.svc.cluster.local"]},{"port":9443,"gateways":["mesh","mesh-gateway.mesh-system.svc.cluster.local"]}],"route":[{"destination":{"host":"xxxxxx.default.svc.cluster.local","subset":"v3","port":{"number":80}},"weight":100}]}]}}'
    objectset.rio.cattle.io/id: routing-service
    objectset.rio.cattle.io/owner-gvk: /, Kind=
    objectset.rio.cattle.io/owner-name: xxxxxx
    objectset.rio.cattle.io/owner-namespace: default
  creationTimestamp: null
  labels:
    objectset.rio.cattle.io/hash: 6eddc47a0f5e8e59d253ec6022892f0331fffc0f
  name: xxxxxx-v3
  namespace: default
spec:
  gateways:
    - mesh
    - mesh-gateway.mesh-system.svc.cluster.local
  hosts:
    - xxxxxx-v3-default
  http:
    - match:
        - gateways:
            - mesh
            - mesh-gateway.mesh-system.svc.cluster.local
          port: 9080
        - gateways:
            - mesh
            - mesh-gateway.mesh-system.svc.cluster.local
          port: 9443
      route:
        - destination:
            host: xxxxxx.default.svc.cluster.local
            port:
              number: 80
            subset: v3
          weight: 100