apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: whoami-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "whoami.default.oauthd.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: whoami
  namespace: default
spec:
  gateways:
    - whoami-gateway
  hosts:
    - whoami.default.oauthd.com
  http:
    - match:
        - gateways:
            - mesh
            - whoami-gateway
          port: 80
        - gateways:
            - mesh
            - whoami-gateway
          port: 443
      route:
        - destination:
            host: whoami.default.svc.cluster.local
            port:
              number: 8000
            subset: v3
          weight: 100

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: whoami
  namespace: default
spec:
  host: whoami.default.svc.cluster.local
  subsets:
    - labels:
        version: v3
      name: v3